### ISSUE TITLE
Docs should note dotnet-sdk-2.1 requirement

### ISSUE THREAD

**Issue by panesofglass** [Arshia001/FSharp.GrpcCodeGenerator#2]
I has some initial trouble getting started, and at least some of the issues were because I didn't have `dotnet-sdk-2.1` installed. After installing that, `protoc-gen-fsharp` seemed to work without throwing an error. Would you mind adding that to the README?

**Comment by Arshia001** [comment]
Sorry, that wasn't intentional. It works with 2.1, 3.1 and 5.0 now.
