### ISSUE TITLE
Release the protoc plugins artifacts

### ISSUE THREAD

**Issue by purkhusid** [Arshia001/FSharp.GrpcCodeGenerator#3]
Hey! I'm really excited to see that you are working on gRPC for F# and I'm curious if you could also release the protoc plugins as release artifacts on the repository? 

I'm currently using F# using Bazel instead of MSBuild and I would like to try creating a Bazel rule that could would use the protoc plugins to generate the F# files.

**Comment by Arshia001** [comment]
The plugin's source is already available. It's contained in the `FSharp.GrpcCodeGenerator` folder. Did you mean something else?

**Comment by brian-scb** [comment]
I think maybe this is a request to add the contents of the `protoc` folder as Assets in a github [release](https://github.com/Arshia001/FSharp.GrpcCodeGenerator/releases).

**Comment by purkhusid** [comment]
I originally wanted to see if it was possible to release the plugin as a single executable but I think it's not going to work since the DLLs are always required. Closing this.
