### ISSUE TITLE
Works on ionide? 

### ISSUE THREAD

**Issue by joshuapassos** [Arshia001/FSharp.GrpcCodeGenerator#5]
I trying to run https://github.com/panesofglass/grpc-fsharp-sample/ and create a simple using the tutorial, but I have 
`The value, namespace, type or module 'Greeter' is not defined. F# Compiler(39)` on ionide

**Comment by Arshia001** [comment]
That's curious. The `Tools` package adds MSBuild scripts which I have seen running on both the full MSBuild and the one contained in .NET Core. Ionide has to be scanning the `fsproj`, so it *should* pick the generated source up. However, the source file must be generated first, which probably means you have to run a build at least once before it starts picking the types up. I'll look into this.

**Comment by Arshia001** [comment]
Upon further investigation, I have found no way to instruct Ionide to scan the generated sources. I've opened an issue.

**Comment by Arshia001** [comment]
I've pinged the Ionide people and ionide/ionide-vscode-fsharp#1535 is open again. Closing since this isn't an FSharp.GrpcCodeGenerator issue.
